service: app
provider:
    name: aws
    runtime: provided.al2
    lambdaHashingVersion: 20201221
    region: ap-northeast-1
plugins:
    - ./vendor/bref/bref
functions:
    app:
        handler: public/index.php
        layers:
            - ${bref:layer.php-80-fpm}
            - arn:aws:lambda:ap-northeast-1:387597514301:layer:lambda-oci8-layer:3
        events:
            - httpApi: '*'
package:
    # Directories to exclude from deployment
    exclude:
        - node_modules/**
        - public/storage
        - resources/assets/**
        - storage/**
        - tests/**
